### PR TITLE
Added try statement to __enter__ in jasp context manager to ensure __exi...

### PR DESCRIPTION
**Pull request by jboes**
...t__ is run regardless of exceptions

Example before:

```javascript
#+BEGIN_SRC python
from jasp import *
import os

print('Starting directory: {0}'.format(os.getcwd()))

try:
    with jasp('unconverged') as calc:
        try:
            calc.calculate()
        except(VaspQueued, VaspSubmitted):
            pass
except:
    print('__exit__ is not run')

print('Ending directory: {0}'.format(os.getcwd()))
#+END_SRC

#+RESULTS:
: Starting directory: /home-research/jboes/errorlog
: __exit__ is not run
: Ending directory: /home-research/jboes/errorlog/unconverged
```

With changes:

```javascript
#+BEGIN_SRC python
from jasp import *
import os

print('Starting directory: {0}'.format(os.getcwd()))

try:
    with jasp('unconverged') as calc:
        try:
            calc.calculate()
        except(VaspQueued, VaspSubmitted):
            pass
except:
    print('Changes ensure __exit__ is always run')

print('Ending directory: {0}'.format(os.getcwd()))
#+END_SRC

#+RESULTS:
: Starting directory: /home-research/jboes/errorlog
: Changes ensure __exit__ is always run
: Ending directory: /home-research/jboes/errorlog
```

Also added pep8 compliant changes.

### CODE REVIEW

**Comment by jkitchin** [comment]
I feel like an alternative to all this is try-catch-finally and avoid
the context manager completely.

try:
    cwd = os.getcwd()
    os.chdir(some-dir)
    calc = Jasp(...) # note capital Jasp
    calc.do something
except (e1):
    jfjfd
except (e2):
    fdkafjkda
finally:
    os.chdir(cwd)

one layer of indentation. no code change required ;) just a few extra
lines. what do you think?

Jacob Boes writes:

> ...t__ is run regardless of exceptions
>
> Example before:
>
> ```javascript
> #+BEGIN_SRC python
> from jasp import *
> import os
>
> print('Starting directory: {0}'.format(os.getcwd()))
>
> try:
>     with jasp('unconverged') as calc:
>         try:
>             calc.calculate()
>         except(VaspQueued, VaspSubmitted):
>             pass
> except:
>     print('__exit__ is not run')
>
> print('Ending directory: {0}'.format(os.getcwd()))
> #+END_SRC
>
> #+RESULTS:
> : Starting directory: /home-research/jboes/errorlog
> : __exit__ is not run
> : Ending directory: /home-research/jboes/errorlog/unconverged
> ```
>
> With changes:
>
> ```javascript
> #+BEGIN_SRC python
> from jasp import *
> import os
>
> print('Starting directory: {0}'.format(os.getcwd()))
>
> try:
>     with jasp('unconverged') as calc:
>         try:
>             calc.calculate()
>         except(VaspQueued, VaspSubmitted):
>             pass
> except:
>     print('Changes ensure __exit__ is always run')
>
> print('Ending directory: {0}'.format(os.getcwd()))
> #+END_SRC
>
> #+RESULTS:
> : Starting directory: /home-research/jboes/errorlog
> : Changes ensure __exit__ is always run
> : Ending directory: /home-research/jboes/errorlog
> ```
>
> Also added pep8 compliant changes.
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/jkitchin/jasp/pull/32
>
> -- Commit Summary --
>
>   * Added try statement to __enter__ in jasp context manager to ensure __exit__ is run regardless of exceptions
>
> -- File Changes --
>
>     M jasp/jasp.py (57)
>
> -- Patch Links --
>
> https://github.com/jkitchin/jasp/pull/32.patch
> https://github.com/jkitchin/jasp/pull/32.diff
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/jasp/pull/32

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by prtkm** [comment]
But the context manager is beautiful! :) I think manually changing
directories can is prone to error, one missed os.chdir(cwd) statement one
will start creating files in the wrong place.

Also, I think quite simple to move the exceptions into the body of the
context manager. I just pushed this
https://github.com/prtkm/jasp/commit/52e224ed5939cea2ddc7ad63df6bd3329e5be7e9.
It now catches VaspNotFinished in the context manager in the desired way.

**Comment by jboes** [comment]
I like both ideas. I think the gold standard for calling jasp would look like this:

```javascript
calc = Jasp('working_directory', 
                    etc...)

try:
    calc.do_something
except (e1):
    jfjfd
except (e2):
    fdkafjkda
```

It seems to me, that you should be able to pass the directory name to the function and have it know to switch to that directory before running any Vasp commands. I'm not sure how feasible that is.

That being said. I'm fine with whatever will allow me to handle all exceptions.

**Comment by jkitchin** [comment]
Jacob Boes writes:

> I like both ideas. I think the gold standard for calling jasp would look like this:
>
> ```javascript
> calc = Jasp('working_directory',
>                     etc...)
>
> try:
>     calc.do_something
> except (e1):
>     jfjfd
> except (e2):
>     fdkafjkda
> ```
>
> It seems to me, that you should be able to pass the directory name to
> the function and have it know to switch to that directory before
> running any Vasp commands. I'm not sure how feasible that is.

This cannot be done robustly, and was the whole point of the context
manager. It is easy to change the directory, but to ensure you always
change back, you need to wrap the whole thing essentially in a
try/catch/finally block.

The "Feature" of the context manager is it happens only in one place, so
we don't have to add them to every function that ever might change
directory. It is too easy to forget one, then months later you have to
track down what function isn't working right! (Voice of experience...)
It could be possible to decorate these functions so that the directory
changing occurs at the function level, but i think the maintenance level
would be higher and harder.

So far the best solution seems to minimize errors from the enter block,
and raise them in the body. That means moving the exception raising code
to functions that actually return data. I will take a look at the
suggestions soon.

>
> That being said. I'm fine with whatever will allow me to handle all exceptions.
>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/jasp/pull/32#issuecomment-74993156

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by prtkm** [comment]
On the subject of elegant syntax, I wanted to ask what the best way to not automatically restart finished but unconverged calculations is. There are multiple reasons that one would want to do this.

Examples:
1. We are doing an geometry optimization and the calc moves towards an undesirable geometry due to a bad initial guess, or it requires a less stringent ediffg value.

2. SCF calculations with lwave and lcharg set as false (to not write wavecar and chgcar files) will always redo the same unconverged calc.

The only way I can think of to do this is:

try:
    if calc.converged:
           do something
    else:
          do something else

except (VaspSubmitted, VaspQueued, VaspNotFinished):
  do something else'

Checking if a calc is converged everytime is tedious. Maybe its more convenient to raise a VaspNotConverged error, and ask the user if a restart is desired?

For example something like:

try:
       do something
except (VaspSubmitted, VaspQueued, VaspNotFinished):
  do something else
except VaspNotConverged:
    calc.set_restart_unconverged(True)
    calc.calculate()

**Comment by jkitchin** [comment]
I have just pushed a new solution that I think works well. It is just a
new context manager that only makes and changes directory. The calc is
created in the body now, so it is free to raise exceptions as it sees
fit. This is what it looks like.


from jasp import *
import os

with cd('ref/c0'):
    print os.getcwd()
    calc = Jasp()
    print calc
print os.getcwd()



Prateek Mehta writes:

> But the context manager is beautiful! :) I think manually changing
> directories can is prone to error, one missed os.chdir(cwd) statement one
> will start creating files in the wrong place.
>
> Also, I think quite simple to move the exceptions into the body of the
> context manager. I just pushed this
> https://github.com/prtkm/jasp/commit/52e224ed5939cea2ddc7ad63df6bd3329e5be7e9.
> It now catches VaspNotFinished in the context manager in the desired way.
>
>
>
> On Wed, Feb 18, 2015 at 7:28 PM, John Kitchin <notifications@github.com>
> wrote:
>
>> I feel like an alternative to all this is try-catch-finally and avoid
>> the context manager completely.
>>
>> try:
>> cwd = os.getcwd()
>> os.chdir(some-dir)
>> calc = Jasp(...) # note capital Jasp
>> calc.do something
>> except (e1):
>> jfjfd
>> except (e2):
>> fdkafjkda
>> finally:
>> os.chdir(cwd)
>>
>> one layer of indentation. no code change required ;) just a few extra
>> lines. what do you think?
>>
>> Jacob Boes writes:
>>
>> > ...t__ is run regardless of exceptions
>> >
>> > Example before:
>> >
>> > ```javascript
>> > #+BEGIN_SRC python
>> > from jasp import *
>> > import os
>> >
>> > print('Starting directory: {0}'.format(os.getcwd()))
>> >
>> > try:
>> > with jasp('unconverged') as calc:
>> > try:
>> > calc.calculate()
>> > except(VaspQueued, VaspSubmitted):
>> > pass
>> > except:
>> > print('__exit__ is not run')
>> >
>> > print('Ending directory: {0}'.format(os.getcwd()))
>> > #+END_SRC
>> >
>> > #+RESULTS:
>> > : Starting directory: /home-research/jboes/errorlog
>> > : __exit__ is not run
>> > : Ending directory: /home-research/jboes/errorlog/unconverged
>> > ```
>> >
>> > With changes:
>> >
>> > ```javascript
>> > #+BEGIN_SRC python
>> > from jasp import *
>> > import os
>> >
>> > print('Starting directory: {0}'.format(os.getcwd()))
>> >
>> > try:
>> > with jasp('unconverged') as calc:
>> > try:
>> > calc.calculate()
>> > except(VaspQueued, VaspSubmitted):
>> > pass
>> > except:
>> > print('Changes ensure __exit__ is always run')
>> >
>> > print('Ending directory: {0}'.format(os.getcwd()))
>> > #+END_SRC
>> >
>> > #+RESULTS:
>> > : Starting directory: /home-research/jboes/errorlog
>> > : Changes ensure __exit__ is always run
>> > : Ending directory: /home-research/jboes/errorlog
>> > ```
>> >
>> > Also added pep8 compliant changes.
>> > You can view, comment on, or merge this pull request online at:
>> >
>> > https://github.com/jkitchin/jasp/pull/32
>> >
>> > -- Commit Summary --
>> >
>> > * Added try statement to __enter__ in jasp context manager to ensure
>> __exit__ is run regardless of exceptions
>> >
>> > -- File Changes --
>> >
>> > M jasp/jasp.py (57)
>> >
>> > -- Patch Links --
>> >
>> > https://github.com/jkitchin/jasp/pull/32.patch
>> > https://github.com/jkitchin/jasp/pull/32.diff
>> >
>> > ---
>> > Reply to this email directly or view it on GitHub:
>> > https://github.com/jkitchin/jasp/pull/32
>>
>> --
>> Professor John Kitchin
>> Doherty Hall A207F
>> Department of Chemical Engineering
>> Carnegie Mellon University
>> Pittsburgh, PA 15213
>> 412-268-7803
>> @johnkitchin
>> http://kitchingroup.cheme.cmu.edu
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jkitchin/jasp/pull/32#issuecomment-74978459>.
>>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/jasp/pull/32#issuecomment-74981624

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by prtkm** [comment]
This sounds great! Do you think it's still wothwhile moving the exception raising code into jasp_extensions, and not during initialization of the calculator?

The potential benefit of this is that calc = Jasp() will still return a calc even if it is unfinished, and will allow us to use attributes which do not depend on the calculation being finished. An error will be raised only when it depends on a finished calculation, e.g get_potential_energy().

**Comment by jkitchin** [comment]
Yes, I think it still worth doing that. it will make the old jasp
context manager work better, so I don't have to rewrite all the code
blocks in dft-book ;)

Prateek Mehta writes:

> This sounds great! Do you think it's still wothwhile moving the exception raising code into jasp_extensions, and not during initialization of the calculator?
>
> The potential benefit of this is that calc = Jasp() will still return a calc even if it is unfinished, and will allow us to use attributes which do not depend on the calculation being finished. An error will be raised only when it depends on a finished calculation, e.g get_potential_energy().
>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/jasp/pull/32#issuecomment-75276515

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Pull request closed without merging**
